import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { v4 as uuidv4 } from 'uuid';

@Injectable({
  providedIn: 'root',
})
export class SyntheticBasestocksService {
  // new BehaviorSubject<any>

  public selectedMainTab: number = 1;
  public selectedPaoMainTab: number = 1;
  public modalData: any[] = [
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '50/90',
      Composition: 0,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '100/130',
      Composition: 1,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '150',
      Composition: 1.3,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '50/90',
      Composition: 0,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '100/130',
      Composition: 1,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '150',
      Composition: 1.3,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '50/90',
      Composition: 0,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '100/130',
      Composition: 1,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '150',
      Composition: 1.3,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '50/90',
      Composition: 0,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '100/130',
      Composition: 1,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '150',
      Composition: 1.3,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '50/90',
      Composition: 0,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '100/130',
      Composition: 1,
    },
    {
      id: uuidv4(),
      'Basestock Group': 'Paraffinic Group I',
      Basestock: '150',
      Composition: 1.3,
    },
  ];
  public sinteticEsterTypeData: any[] = [
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      sinteticEster: 'Polyol',
      value: 2,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      sinteticEster: 'Polyol',
      value: 7,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      sinteticEster: 'Mono',
      value: 4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      sinteticEster: 'Other',
      value: 8,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      sinteticEster: 'Polyol',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      sinteticEster: 'Diester',
      value: 18,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      sinteticEster: 'Mono',
      value: 3,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      sinteticEster: 'Other',
      value: 6.1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      sinteticEster: 'Polyol',
      value: 11.4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      sinteticEster: 'Diester',
      value: 9.2,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      sinteticEster: 'Other',
      value: 4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Other',
      value: 1,
    },

    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      sinteticEster: 'Other',
      value: 1,
    },

    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      sinteticEster: 'Other',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      sinteticEster: 'Polyol',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      sinteticEster: 'Diester',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      sinteticEster: 'Mono',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      sinteticEster: 'Other',
      value: 1,
    },
  ];

  public PAGEsterTypeData: any[] = [
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 2,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'PCMO',
      pagEster: 'PPG',
      value: 100,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 7,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      pagEster: 'PEG',
      value: 4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HDMO',
      pagEster: 'PPG',
      value: 8,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      pagEster: 'Random Polymers of EO/PO',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      pagEster: 'Block Polymers of EO/PO',
      value: 18,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      pagEster: 'PEG',
      value: 3,
    },
    {
      segment: 'Consumer Automotive',
      product: '2T/4T',
      pagEster: 'PPG',
      value: 6.1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      pagEster: 'Random Polymers of EO/PO',
      value: 11.4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      pagEster: 'Block Polymers of EO/PO',
      value: 9.2,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'ATF',
      pagEster: 'PPG',
      value: 4,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Grease',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Gear Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'HTF',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'General Industrial Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Consumer Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'PPG',
      value: 1,
    },

    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'PCMO',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HDMO',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: '2T/4T',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'ATF',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Grease',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Gear Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'HTF',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'General Industrial Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Industrial Engine Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Commercial Automotive',
      product: 'Metalworking Fluid',
      pagEster: 'PPG',
      value: 1,
    },

    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'PCMO',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HDMO',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: '2T/4T',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'ATF',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Grease',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Gear Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'HTF',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'General Industrial Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Industrial Engine Oil',
      pagEster: 'PPG',
      value: 1,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      pagEster: 'Random Polymers of EO/PO',
      value: 12,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      pagEster: 'Block Polymers of EO/PO',
      value: 10,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      pagEster: 'PEG',
      value: 5,
    },
    {
      segment: 'Industrial Oils and Fluids',
      product: 'Metalworking Fluid',
      pagEster: 'PPG',
      value: 1,
    },
  ];
  constructor() {}

  setSelectedMainTab(data: number): void {
    this.selectedMainTab = data;
    console.log('this.selectedMainTab', this.selectedMainTab);
  }

  getSelectedMainTab(): any {
    return this.selectedMainTab;
  }
  setSelectedPaoMainTab(data: number): void {
    this.selectedPaoMainTab = data;
    console.log('this.selectedPaoMainTab', this.selectedPaoMainTab);
  }

  getSelectedPaoMainTab(): any {
    return this.selectedPaoMainTab;
  }
}
