import { Injectable } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

@Injectable({
  providedIn: 'root',
})
export class RrboService {
  public europeCountries: any[] = [
    'WesternEurope',
    'Russia'
  ]
  public northAmericaCountries: any[] = [
    'Brazil'
  ]
  public southAmericaCountries: any[] = [
    'USA',
    'Mexico',
    'Canada'
  ]
  public africaCountries: any[] = []
  public asiaCountries: any[] = [
    'India',
    'China',
    'Indonesia',
    'Japan',
    'SouthKorea',
    'Thailand',
    'Malaysia'
  ]
  public reguliarSummary: any[] = [
    {
      question: 'Are there any requirements on who can collect used oil?​',
      USA: 'Yes',
      Brazil: 'Yes',
      India: 'Yes',
      China: 'Yes',
      Indonesia: 'Yes',
      Japan: 'Yes',
      Malaysia: 'Yes',
      Mexico: 'Yes',
      Russia: 'Yes',
      SouthKorea: 'Yes',
      Thailand: 'Yes',
      Canada: 'Yes',
      WesternEurope: 'Yes',
    },
    {
      question: 'Do regulations exist specifically for used oil?​​',
      USA: 'Yes',
      Brazil: 'Yes',
      India: 'Yes',
      China: 'Yes',
      Indonesia: 'Yes',
      Japan: 'Yes',
      Malaysia: 'Yes',
      Mexico: 'Yes',
      Russia: 'Yes',
      SouthKorea: 'Yes',
      Thailand: 'Yes',
      Canada: 'Yes',
      WesternEurope: 'Yes',
    },
    {
      question:
        ' How is used oil classified i.e., hazardous waste, special waste etc.?​​​',
      USA: 'Special Waste, not Hazardous Waste​',
      Brazil: 'Special Waste, not Hazardous Waste​',
      India: 'Special Waste, not Hazardous Waste​',
      China: 'Special Waste, not Hazardous Waste​',
      Indonesia: 'Special Waste, not Hazardous Waste​',
      Japan: 'Special Waste, not Hazardous Waste​',
      Malaysia: 'Special Waste, not Hazardous Waste​',
      Mexico: 'Special Waste, not Hazardous Waste​',
      Russia: 'Special Waste, not Hazardous Waste​',
      SouthKorea: 'Special Waste, not Hazardous Waste​',
      Thailand: 'Special Waste, not Hazardous Waste​',
      Canada: 'Special Waste, not Hazardous Waste​',
      WesternEurope: 'Special Waste, not Hazardous Waste​',
    },
    {
      question:
        'Does the country have any legislation that requires used oil to be re-refined?​',
      USA: 'No',
      Brazil: 'No',
      India: 'No',
      China: 'No',
      Indonesia: 'No',
      Japan: 'No',
      Malaysia: 'No',
      Mexico: 'No',
      Russia: 'No',
      SouthKorea: 'No',
      Thailand: 'No',
      Canada: 'No',
      WesternEurope: 'No',
    },
    {
      question:
        'Does country have an association(s) managing the collection and disposal of used oil? ​​',
      USA: 'NORA represents the industry but does not manage collection or use​',
      Brazil:
        'NORA represents the industry but does not manage collection or use​',
      India:
        'NORA represents the industry but does not manage collection or use​',
      China:
        'NORA represents the industry but does not manage collection or use​',
      Indonesia:
        'NORA represents the industry but does not manage collection or use​',
      Japan:
        'NORA represents the industry but does not manage collection or use​',
      Malaysia:
        'NORA represents the industry but does not manage collection or use​',
      Mexico:
        'NORA represents the industry but does not manage collection or use​',
      Russia:
        'NORA represents the industry but does not manage collection or use​',
      SouthKorea:
        'NORA represents the industry but does not manage collection or use​',
      Thailand:
        'NORA represents the industry but does not manage collection or use​',
      Canada:
        'NORA represents the industry but does not manage collection or use​',
      WesternEurope:
        'NORA represents the industry but does not manage collection or use​',
    },
    {
      question:
        'Is a levy charged on sales of lubricants to support used oil collection associations?​​',
      USA: 'Not at the Federal level​',
      Brazil: 'Not at the Federal level​',
      India: 'Not at the Federal level​',
      China: 'Not at the Federal level​',
      Indonesia: 'Not at the Federal level​',
      Japan: 'Not at the Federal level​',
      Malaysia: 'Not at the Federal level​',
      Mexico: 'Not at the Federal level​',
      Russia: 'Not at the Federal level​',
      SouthKorea: 'Not at the Federal level​',
      Thailand: 'Not at the Federal level​',
      Canada: 'Not at the Federal level​',
      WesternEurope: 'Not at the Federal level​',
    },
    {
      question:
        'Does the country have requirements or regulations regarding the export or import of used oil?​​',
      USA: 'Not specific to UO​',
      Brazil: 'Not specific to UO​',
      India: 'Not specific to UO​',
      China: 'Not specific to UO​',
      Indonesia: 'Not specific to UO​',
      Japan: 'Not specific to UO​',
      Malaysia: 'Not specific to UO​',
      Mexico: 'Not specific to UO​',
      Russia: 'Not specific to UO​',
      SouthKorea: 'Not specific to UO​',
      Thailand: 'Not specific to UO​',
      Canada: 'Not specific to UO​',
      WesternEurope: 'Not specific to UO​',
    },
    {
      question:
        'Are there any requirements for how used oil generators manage used oil? ​​',
      USA: 'Yes',
      Brazil: 'Yes',
      India: 'Yes',
      China: 'Yes',
      Indonesia: 'Yes',
      Japan: 'Yes',
      Malaysia: 'Yes',
      Mexico: 'Yes',
      Russia: 'Yes',
      SouthKorea: 'Yes',
      Thailand: 'Yes',
      Canada: 'Yes',
      WesternEurope: 'Yes',
    },
    {
      question:
        'Are there requirements for oil manufacturers, marketers, or retailers to take back used oil?​​​',
      USA: 'No',
      Brazil: 'No',
      India: 'No',
      China: 'No',
      Indonesia: 'No',
      Japan: 'No',
      Malaysia: 'No',
      Mexico: 'No',
      Russia: 'No',
      SouthKorea: 'No',
      Thailand: 'No',
      Canada: 'No',
      WesternEurope: 'No',
    },
    {
      question:
        'Do any requirements/legislation exist around different types of used oil?​​​',
      USA: 'Yes',
      Brazil: 'Yes',
      India: 'Yes',
      China: 'Yes',
      Indonesia: 'Yes',
      Japan: 'Yes',
      Malaysia: 'Yes',
      Mexico: 'Yes',
      Russia: 'Yes',
      SouthKorea: 'Yes',
      Thailand: 'Yes',
      Canada: 'Yes',
      WesternEurope: 'Yes',
    },
    {
      question:
        'Does the country have legislation that requires lubricating oil to contain a percentage of re-refined basestock?​​​​',
      USA: 'No',
      Brazil: 'No',
      India: 'No',
      China: 'No',
      Indonesia: 'No',
      Japan: 'No',
      Malaysia: 'No',
      Mexico: 'No',
      Russia: 'No',
      SouthKorea: 'No',
      Thailand: 'No',
      Canada: 'No',
      WesternEurope: 'No',
    },
    {
      question:
        'Does the country have legislation that gives incentives, financial subsidies or priority to any particular Used Oil disposition – e.g., re-refining, fuel for burning, landfill etc.​​',
      USA: 'Not at the federal level​',
      Brazil: 'Not at the federal level​',
      India: 'Not at the federal level​',
      China: 'Not at the federal level​',
      Indonesia: 'Not at the federal level​',
      Japan: 'Not at the federal level​',
      Malaysia: 'Not at the federal level​',
      Mexico: 'Not at the federal level​',
      Russia: 'Not at the federal level​',
      SouthKorea: 'Not at the federal level​',
      Thailand: 'Not at the federal level​',
      Canada: 'Not at the federal level​',
      WesternEurope: 'Not at the federal level​',
    },
    {
      question: 'no title ​​​',
      USA: 'ii. Blending with crude oil at a refinery​-Allowed',
      Brazil: 'ii. Blending with crude oil at a refinery​-Allowed',
      India: 'ii. Blending with crude oil at a refinery​-Allowed',
      China: 'ii. Blending with crude oil at a refinery​-Allowed',
      Indonesia: 'ii. Blending with crude oil at a refinery​-Allowed',
      Japan: 'ii. Blending with crude oil at a refinery​-Allowed',
      Malaysia: 'ii. Blending with crude oil at a refinery​-Allowed',
      Mexico: 'ii. Blending with crude oil at a refinery​-Allowed',
      Russia: 'ii. Blending with crude oil at a refinery​-Allowed',
      SouthKorea: 'ii. Blending with crude oil at a refinery​-Allowed',
      Thailand: 'ii. Blending with crude oil at a refinery​-Allowed',
      Canada: 'ii. Blending with crude oil at a refinery​-Allowed',
      WesternEurope: 'ii. Blending with crude oil at a refinery​-Allowed',
    },
    {
      question: 'Is used oil allowed to be placed in a landfill?​​​​',
      USA: 'No​',
      Brazil: 'No​',
      India: 'No​',
      China: 'No​',
      Indonesia: 'No​',
      Japan: 'No​',
      Malaysia: 'No​',
      Mexico: 'No​',
      Russia: 'No​',
      SouthKorea: 'No​',
      Thailand: 'No​',
      Canada: 'No​',
      WesternEurope: 'No​',
    },
    {
      question:
        ' Does the country allow used oil to be burned as a fuel (cement kilns, industrial boilers or furnaces, power plants, etc.)?​​​​',
      USA: 'Yes​',
      Brazil: 'Yes​',
      India: 'Yes​',
      China: 'Yes​',
      Indonesia: 'Yes​',
      Japan: 'Yes​',
      Malaysia: 'Yes​',
      Mexico: 'Yes​',
      Russia: 'Yes​',
      SouthKorea: 'Yes​',
      Thailand: 'Yes​',
      Canada: 'Yes​',
      WesternEurope: 'Yes​',
    },
    {
      question: 'no title ​​​',
      USA: 'iii. Dust suppressant​-Prohibited',
      Brazil: 'iii. Dust suppressant​-Prohibited',
      India: 'iii. Dust suppressant​-Prohibited',
      China: 'iii. Dust suppressant​-Prohibited',
      Indonesia: 'iii. Dust suppressant​-Prohibited',
      Japan: 'iii. Dust suppressant​-Prohibited',
      Malaysia: 'iii. Dust suppressant​-Prohibited',
      Mexico: 'iii. Dust suppressant​-Prohibited',
      Russia: 'iii. Dust suppressant​-Prohibited',
      SouthKorea: 'iii. Dust suppressant​-Prohibited',
      Thailand: 'iii. Dust suppressant​-Prohibited',
      Canada: 'iii. Dust suppressant​-Prohibited',
      WesternEurope: 'iii. Dust suppressant​-Prohibited',
    },
    {
      question:
        'If used oil can be burned as a fuel, is the fuel burner subject to a different and more stringent set of air emissions requirements (relative to operating without burning used oil as a fuel) or must the fuel burner install additional pollution control equipment or energy recovery equipment before it can burn the used oil?​ ​​​',
      USA: 'Not at the federal level​',
      Brazil: 'Not at the federal level​',
      India: 'Not at the federal level​',
      China: 'Not at the federal level​',
      Indonesia: 'Not at the federal level​',
      Japan: 'Not at the federal level​',
      Malaysia: 'Not at the federal level​',
      Mexico: 'Not at the federal level​',
      Russia: 'Not at the federal level​',
      SouthKorea: 'Not at the federal level​',
      Thailand: 'Not at the federal level​',
      Canada: 'Not at the federal level​',
      WesternEurope: 'Not at the federal level​',
    },
    {
      question:
        ' Please indicate whether used oil can be legally used (i.e., regulations do not prohibit) for the following purposes, assuming that used oil is not being mixed first with a hazardous waste:​​​​',
      USA: 'i.  Burning in space heaters​-Allowed',
      Brazil: 'i.  Burning in space heaters​-Allowed',
      India: 'i.  Burning in space heaters​-Allowed',
      China: 'i.  Burning in space heaters​-Allowed',
      Indonesia: 'i.  Burning in space heaters​-Allowed',
      Japan: 'i.  Burning in space heaters​-Allowed',
      Malaysia: 'i.  Burning in space heaters​-Allowed',
      Mexico: 'i.  Burning in space heaters​-Allowed',
      Russia: 'i.  Burning in space heaters​-Allowed',
      SouthKorea: 'i.  Burning in space heaters​-Allowed',
      Thailand: 'i.  Burning in space heaters​-Allowed',
      Canada: 'i.  Burning in space heaters​-Allowed',
      WesternEurope: 'i.  Burning in space heaters​-Allowed',
    },
    {
      question:
        ' Are there companies/associations advocating in used oil category?​​​​',
      USA: 'Yes​',
      Brazil: 'Yes​',
      India: 'Yes​',
      China: 'Yes​',
      Indonesia: 'Yes​',
      Japan: 'Yes​',
      Malaysia: 'Yes​',
      Mexico: 'Yes​',
      Russia: 'Yes​',
      SouthKorea: 'Yes​',
      Thailand: 'Yes​',
      Canada: 'Yes​',
      WesternEurope: 'Yes​',
    },
  ];
  constructor() {}
}
